
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/syb/Downloads/project/Log_Analysis_AI_Assistant/test_tmp/sample_logs/*.log
  fields:
    log_type: vpn
  fields_under_root: true

output.kafka:
  hosts: ["localhost:9092"]
  topic: "logs_raw"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip

logging.level: warning
logging.to_files: true
logging.files:
  path: /home/syb/Downloads/project/Log_Analysis_AI_Assistant/test_tmp/filebeat_logs
  name: filebeat
  keepfiles: 7
