"""
Streamlit 可视化仪表板 - 基于真实数据
整合了日志解析模块和 ClickHouse 真实数据源
"""

import sys
import os
from pathlib import Path
from datetime import datetime, timedelta
import pandas as pd
import streamlit as st
from fpdf import FPDF
import io
import time

# 添加项目根目录到 sys.path (让 dashboard 能导入 utils.config)
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# 尝试加载 .env 文件
try:
    from dotenv import load_dotenv
    load_dotenv(PROJECT_ROOT / '.env')
except ImportError:
    pass

# 导入配置（提供默认值，但优先使用环境变量）
try:
    from src.utils.config import settings
    # 如果 settings 中定义的数据库是 log_analysis，但实际测试用的是 test_logs，允许从环境变量覆盖
    CLICKHOUSE_DATABASE = os.getenv("CLICKHOUSE_DATABASE", settings.clickhouse_database)
    # 但如果默认值还是 log_analysis，且环境变量没有设置，则强制改为 test_logs（因为测试环境一直用这个）
    if CLICKHOUSE_DATABASE == "log_analysis" and not os.getenv("CLICKHOUSE_DATABASE"):
        CLICKHOUSE_DATABASE = "test_logs"
    CLICKHOUSE_HOST = os.getenv("CLICKHOUSE_HOST", settings.clickhouse_host)
    CLICKHOUSE_PORT = int(os.getenv("CLICKHOUSE_PORT", settings.clickhouse_port))
    CLICKHOUSE_USER = os.getenv("CLICKHOUSE_USER", settings.clickhouse_user)
    CLICKHOUSE_PASSWORD = os.getenv("CLICKHOUSE_PASSWORD", settings.clickhouse_password)
except ImportError:
    # 如果无法导入配置模块，直接从环境变量读取
    CLICKHOUSE_HOST = os.getenv("CLICKHOUSE_HOST", "localhost")
    CLICKHOUSE_PORT = int(os.getenv("CLICKHOUSE_PORT", 8123))
    CLICKHOUSE_DATABASE = os.getenv("CLICKHOUSE_DATABASE", "test_logs")
    CLICKHOUSE_USER = os.getenv("CLICKHOUSE_USER", "default")
    CLICKHOUSE_PASSWORD = os.getenv("CLICKHOUSE_PASSWORD", "")

# 确保使用的数据库是 test_logs（与测试脚本一致）
if CLICKHOUSE_DATABASE != "test_logs":
    st.warning(f"当前配置的数据库是 {CLICKHOUSE_DATABASE}，但测试数据在 test_logs 中，已自动切换")
    CLICKHOUSE_DATABASE = "test_logs"

# 导入 ClickHouse 客户端
try:
    from clickhouse_connect import get_client
except ImportError:
    st.error("请安装 clickhouse-connect: pip install clickhouse-connect")
    st.stop()

# 缓存 ClickHouse 客户端（避免重复连接）
@st.cache_resource
def init_ch_client():
    try:
        client = get_client(
            host=CLICKHOUSE_HOST,
            port=CLICKHOUSE_PORT,
            username=CLICKHOUSE_USER,
            password=CLICKHOUSE_PASSWORD,
            database=CLICKHOUSE_DATABASE,
            compress=True
        )
        # 测试连接
        client.command("SELECT 1")
        return client
    except Exception as e:
        st.error(f"连接 ClickHouse 失败: {e}")
        st.info("请确保已运行测试脚本生成数据，并且 ClickHouse 容器正在运行。")
        st.stop()

ch_client = init_ch_client()

# 页面设置
st.set_page_config(
    page_title="日志分析 AI 助手",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# 辅助函数：生成 PDF 报告（保留原样，可稍后增强）
def generate_pdf_report(report_type, data=None):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Security Report", 0, 1, 'C')
    pdf.ln(10)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
    pdf.ln(5)
    pdf.cell(0, 10, "Report generated by Log Analysis AI Assistant", 0, 1)
    pdf_output = io.BytesIO()
    pdf_output.write(pdf.output(dest='S').encode('latin-1', errors='ignore'))
    pdf_output.seek(0)
    return pdf_output

def init_session_state():
    if "current_page" not in st.session_state:
        st.session_state.current_page = "实时日志流"
    if "logs_data" not in st.session_state:
        st.session_state.logs_data = []

def create_sidebar():
    with st.sidebar:
        st.markdown("---")
        st.subheader("📋 功能导航")
        pages = {
            "实时日志流": "📡",
            "UEBA 异常排行": "👥",
            "安全评分看板": "🛡️",
            "AI 处置建议": "🤖",
            "历史查询": "🔍"
        }
        for page, icon in pages.items():
            if st.button(f"{icon} {page}", use_container_width=True,
                        type="primary" if st.session_state.current_page == page else "secondary"):
                st.session_state.current_page = page
                st.rerun()
        st.markdown("---")
        # 真实的统计指标（从 ClickHouse 获取）
        try:
            total_today = ch_client.query(f"""
                SELECT count() FROM {CLICKHOUSE_DATABASE}.structured_logs
                WHERE toDate(timestamp) = today()
            """).first_row[0]
            total_anomaly = ch_client.query(f"""
                SELECT count() FROM {CLICKHOUSE_DATABASE}.structured_logs
                WHERE toDate(timestamp) = today() AND severity_level IN ('ERROR','CRITICAL')
            """).first_row[0]
            st.metric("今日日志总量", f"{total_today:,}")
            st.metric("异常事件数", f"{total_anomaly:,}")
        except Exception:
            st.metric("今日日志总量", "N/A")
            st.metric("异常事件数", "N/A")
        st.markdown("---")
        st.caption("© 2025 日志分析 AI 助手")

# ---------------------------- 页面实现 ----------------------------
def show_realtime_logs():
    st.header("📡 实时日志流")
    st.markdown("最近入库的结构化日志（点击刷新）")
    col1, col2 = st.columns([3,1])
    with col2:
        if st.button("🔄 刷新", use_container_width=True):
            st.rerun()
    # 从 ClickHouse 查询最近 50 条日志
    df = ch_client.query_df(f"""
        SELECT timestamp, log_type, username, action, source_ip, severity_level
        FROM {CLICKHOUSE_DATABASE}.structured_logs
        ORDER BY timestamp DESC
        LIMIT 50
    """)
    if df.empty:
        st.info("暂无日志数据，请先运行测试脚本生成日志。")
    else:
        # 美化显示
        st.dataframe(df, use_container_width=True, height=500)

def show_ueba_ranking():
    st.header("👥 UEBA 异常用户排行")
    time_range = st.selectbox("时间范围", ["最近 24 小时", "最近 7 天"], index=0)
    if time_range == "最近 24 小时":
        interval = "INTERVAL 1 DAY"
    else:
        interval = "INTERVAL 7 DAY"
    query = f"""
        SELECT 
            username,
            count() as event_count,
            countIf(severity_level IN ('ERROR','CRITICAL')) as anomaly_count,
            round(anomaly_count / event_count, 2) as anomaly_ratio
        FROM {CLICKHOUSE_DATABASE}.structured_logs
        WHERE timestamp >= now() - {interval}
        GROUP BY username
        HAVING anomaly_count > 0
        ORDER BY anomaly_ratio DESC, anomaly_count DESC
        LIMIT 10
    """
    df = ch_client.query_df(query)
    if df.empty:
        st.info("暂无异常用户数据")
    else:
        st.dataframe(df, use_container_width=True)
        # 可选：展示选中用户的详情
        selected = st.selectbox("查看用户详情", df['username'].tolist())
        if selected:
            detail_df = ch_client.query_df(f"""
                SELECT timestamp, log_type, action, source_ip, severity_level, detail
                FROM {CLICKHOUSE_DATABASE}.structured_logs
                WHERE username = '{selected}'
                ORDER BY timestamp DESC
                LIMIT 20
            """)
            st.write(f"用户 {selected} 的最新异常事件")
            st.dataframe(detail_df, use_container_width=True)

def show_security_score():
    st.header("🛡️ 安全评分看板")
    # 真实指标
    try:
        total_today = ch_client.query(f"SELECT count() FROM {CLICKHOUSE_DATABASE}.structured_logs WHERE toDate(timestamp) = today()").first_row[0]
        anomaly_today = ch_client.query(f"SELECT count() FROM {CLICKHOUSE_DATABASE}.structured_logs WHERE toDate(timestamp) = today() AND severity_level IN ('ERROR','CRITICAL')").first_row[0]
        high_risk_users = ch_client.query(f"""
            SELECT count(DISTINCT username) FROM {CLICKHOUSE_DATABASE}.structured_logs
            WHERE toDate(timestamp) = today() AND severity_level = 'CRITICAL'
        """).first_row[0]
        resolved = ch_client.query(f"SELECT count() FROM {CLICKHOUSE_DATABASE}.structured_logs WHERE parse_status = 'success' AND toDate(timestamp) = today()").first_row[0]
        # 安全评分（简单算法）
        score = max(0, 100 - (anomaly_today * 5) - (high_risk_users * 10))
        score = min(100, score)
    except Exception:
        total_today = 0
        anomaly_today = 0
        high_risk_users = 0
        resolved = 0
        score = 0

    col1, col2, col3, col4 = st.columns(4)
    with col1: st.metric("整体安全评分", f"{score}/100")
    with col2: st.metric("今日异常事件", anomaly_today)
    with col3: st.metric("高危用户数", high_risk_users)
    with col4: st.metric("已处置事件", resolved)

    # 趋势图
    st.subheader("📈 安全评分趋势（最近 7 天）")
    df_trend = ch_client.query_df(f"""
        SELECT toDate(timestamp) as date, countIf(severity_level IN ('ERROR','CRITICAL')) as anomalies
        FROM {CLICKHOUSE_DATABASE}.structured_logs
        WHERE timestamp >= today() - INTERVAL 7 DAY
        GROUP BY date
        ORDER BY date
    """)
    if not df_trend.empty:
        st.line_chart(df_trend.set_index('date')['anomalies'])
    else:
        st.info("暂无趋势数据")

    # 风险分布
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("⚠️ 风险等级分布")
        risk_df = ch_client.query_df(f"""
            SELECT severity_level, count() as cnt
            FROM {CLICKHOUSE_DATABASE}.structured_logs
            WHERE toDate(timestamp) = today()
            GROUP BY severity_level
        """)
        if not risk_df.empty:
            st.bar_chart(risk_df.set_index('severity_level'))
        else:
            st.info("暂无数据")
    with col2:
        st.subheader("🎯 日志类型分布")
        type_df = ch_client.query_df(f"""
            SELECT log_type, count() as cnt
            FROM {CLICKHOUSE_DATABASE}.structured_logs
            WHERE toDate(timestamp) = today()
            GROUP BY log_type
        """)
        if not type_df.empty:
            st.bar_chart(type_df.set_index('log_type'))
        else:
            st.info("暂无数据")

    # 生成日报按钮
    if st.button("📊 生成今日安全简报", type="primary"):
        st.info("今日安全简报（基于真实数据）生成中...")
        st.markdown(f"""
        **今日安全态势简报**
        - 整体安全评分: {score}/100
        - 日志总量: {total_today}
        - 异常事件: {anomaly_today}
        - 高危用户: {high_risk_users}
        - 已处置: {resolved}
        """)
        pdf_data = generate_pdf_report("security")
        st.download_button("下载 PDF 报告", pdf_data, f"security_{datetime.now().strftime('%Y%m%d')}.pdf")

def show_ai_suggestions():
    st.header("🤖 AI 处置建议")
    st.info("当前建议基于规则生成（后续可接入大模型）")
    # 获取今日高危用户
    high_risk_users = ch_client.query_df(f"""
        SELECT 
            username, 
            count() as cnt,
            groupArray(10)(action) as actions
        FROM {CLICKHOUSE_DATABASE}.structured_logs
        WHERE toDate(timestamp) = today() AND severity_level = 'CRITICAL'
        GROUP BY username
        ORDER BY cnt DESC
        LIMIT 10
    """)
    if high_risk_users.empty:
        st.success("今日无高危用户，安全态势良好")
    else:
        for idx, row in high_risk_users.iterrows():
            with st.expander(f"🔴 高危用户: {row['username']} (异常事件数: {row['cnt']})"):
                st.markdown(f"**AI 分析**: 该用户今日出现 {row['cnt']} 次严重事件，行为包括 {', '.join(row['actions'][:3])}")
                st.markdown("**处置建议**: 立即冻结账号，联系用户确认，调查来源 IP")
                col1, col2 = st.columns(2)
                with col1:
                    if st.button("标记为误报", key=f"fp_{idx}"):
                        st.success("已标记为误报")
                with col2:
                    if st.button("查看详细日志", key=f"detail_{idx}"):
                        logs = ch_client.query_df(f"""
                            SELECT timestamp, log_type, action, source_ip, detail
                            FROM {CLICKHOUSE_DATABASE}.structured_logs
                            WHERE username = '{row['username']}' AND toDate(timestamp) = today()
                            ORDER BY timestamp DESC
                            LIMIT 10
                        """)
                        st.dataframe(logs)

def show_history_search():
    st.header("🔍 历史日志查询")
    col1, col2 = st.columns(2)
    with col1:
        start_date = st.date_input("开始日期", value=datetime.now() - timedelta(days=7))
        username = st.text_input("用户名 (可选)")
    with col2:
        end_date = st.date_input("结束日期", value=datetime.now())
        severity = st.selectbox("严重程度", ["全部", "INFO", "WARNING", "ERROR", "CRITICAL"])
    if st.button("🔍 查询", type="primary"):
        where_clauses = [f"timestamp >= '{start_date}'", f"timestamp <= '{end_date}' + INTERVAL 1 DAY"]
        if username:
            where_clauses.append(f"username = '{username}'")
        if severity != "全部":
            where_clauses.append(f"severity_level = '{severity}'")
        where_sql = " AND ".join(where_clauses)
        df = ch_client.query_df(f"""
            SELECT timestamp, log_type, username, action, source_ip, severity_level, detail
            FROM {CLICKHOUSE_DATABASE}.structured_logs
            WHERE {where_sql}
            ORDER BY timestamp DESC
            LIMIT 1000
        """)
        if df.empty:
            st.info("未找到匹配的日志")
        else:
            st.dataframe(df, use_container_width=True, height=400)
            csv = df.to_csv(index=False).encode('utf-8')
            st.download_button("导出 CSV", csv, "logs.csv", "text/csv")

# 主函数
def main():
    init_session_state()
    create_sidebar()
    if st.session_state.current_page == "实时日志流":
        show_realtime_logs()
    elif st.session_state.current_page == "UEBA 异常排行":
        show_ueba_ranking()
    elif st.session_state.current_page == "安全评分看板":
        show_security_score()
    elif st.session_state.current_page == "AI 处置建议":
        show_ai_suggestions()
    elif st.session_state.current_page == "历史查询":
        show_history_search()

if __name__ == "__main__":
    main()